import = ["~/.config/alacritty/colors/everforest_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 1.0

[window.padding]
x = 15
y = 10

[font]
size = 11

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"
